version: '3.7'

services:
  node1:
    build: .
    ports:
      - "8001:8001"
    environment:
      # PENTING: Gunakan nama service sebagai host di Docker.
      # Di Docker, node1 tidak bisa mengakses localhost:8002/8003
      - PORT=8001
      - HOST=0.0.0.0
      - BOOTSTRAP_PEERS=node2:8002,node3:8003
    command: uvicorn src.app:app --host 0.0.0.0 --port 8001 --reload

  node2:
    build: .
    ports:
      - "8002:8002"
    environment:
      - PORT=8002
      - HOST=0.0.0.0
      - BOOTSTRAP_PEERS=node1:8001,node3:8003
    command: uvicorn src.app:app --host 0.0.0.0 --port 8002 --reload

  node3:
    build: .
    ports:
      - "8003:8003"
    environment:
      - PORT=8003
      - HOST=0.0.0.0
      - BOOTSTRAP_PEERS=node1:8001,node2:8002
    command: uvicorn src.app:app --host 0.0.0.0 --port 8003 --reload